services:
  mesh-visualizer:
    image: meshtastic_mesh_visualizer
    container_name: meshtastic_mesh_visualizer
    ports:
      - 5000:5000
    volumes:
      - ~/mesh-monitor/data:/data
    environment:
      - MESH_DATA_FILE=/data/mesh_data.json